ARG PYTORCH="1.9.0"
ARG CUDA="11.1"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel AS pytorch-builder

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3.7 -m venv /home/venv
ENV PATH="/home/venv/bin:$PATH"
ENV VIRTUAL_ENV=/home/venv

RUN mkdir /home/yolov
WORKDIR /home/yolov
COPY . .
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir numpy==1.21.6
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install -e .

ENV PYTHONUNBUFFERED=1
